#ifndef NEBULAE_ALPHA_RENDERSYSTEM_OPERATIONTYPE_H_
#define NEBULAE_ALPHA_RENDERSYSTEM_OPERATIONTYPE_H_

namespace Nebulae
{

enum OperationType
{
  OT_UNKNOWN = -1,
  OT_POINTS,
  OT_LINES,
  OT_LINE_STRIP,
  OT_LINELIST = OT_LINE_STRIP, // Compatibility alias.
  OT_TRIANGLES,
  OT_TRIANGLE_STRIP,
  OT_TRIANGLELIST = OT_TRIANGLE_STRIP, // Compatibility alias.
  OT_TRIANGLEFAN
};

}

#endif // NEBULAE_ALPHA_RENDERSYSTEM_OPERATIONTYPE_H_