#ifndef NEBULAE_ALPHA_RENDERSYSTEM_OPERATIONTYPE_H_
#define NEBULAE_ALPHA_RENDERSYSTEM_OPERATIONTYPE_H_

namespace Nebulae
{

enum OperationType
{
  OT_UNKNOWN = -1,
  OT_POINTS,
  OT_LINES,
  OT_LINELIST,
  OT_TRIANGLES,
  OT_TRIANGLELIST,
  OT_TRIANGLEFAN
};

}

#endif // NEBULAE_ALPHA_RENDERSYSTEM_OPERATIONTYPE_H_