load("@rules_cc//cc:defs.bzl", "cc_binary")

# ============================================================================
# BUILD.bazel — Application Sample
# Samples/Application/BUILD.bazel
# ============================================================================

cc_binary(
    name = "application",
    srcs = glob(["*.cpp", "*.h"]),
    data = glob(["*.vsh", "*.fsh"]) + ["//RenderSystems/GL:nebulous_gl3"],
    linkopts = ["/SUBSYSTEM:WINDOWS", "/ENTRY:WinMainCRTStartup"],
    deps = ["//Source/Nebulae:nebulae"],
)
