load("@rules_cc//cc:defs.bzl", "cc_binary")

# ============================================================================
# BUILD.bazel — Simple Sample
# Samples/Simple/BUILD.bazel
# ============================================================================

cc_binary(
    name = "simple",
    srcs = glob(["*.cpp", "*.h"]),
    data = glob(["*.glsl", "*.vsh", "*.fsh"]) + ["//RenderSystems/GL:nebulous_gl3"],
    linkopts = ["/SUBSYSTEM:WINDOWS", "/ENTRY:WinMainCRTStartup"],
    deps = ["//Source/Nebulae:nebulae"],
)
